### PR TITLE
Changed config filename from `miden.toml` to `node.toml`

### PR DESCRIPTION
**Pull request by phklive**
I had previously mistakenly pushed this PR to main, I have reverted it promptly and opened this PR in a new branch here.

@bobbinth should we include branch protection rules on our repos to prevent push to main or other errors related to branching from happening in the future?

This PR closes: #205

### CODE REVIEW

**Comment by phklive** [comment]
In this PR I have change the naming from `miden.toml` to `node.toml` if requested I can change it to `miden-node.toml`, I have added my rational here: https://github.com/0xPolygonMiden/miden-node/issues/205#issuecomment-1929333596

I believe that we should have a naming convention accross repos for config files.

**Review by polydez — APPROVED** [review]
Looks good to me! :)

**Comment by bobbinth** [comment]
Not a strong preference, but I do like a slightly more explicit name better (i.e., `miden-node.toml`). Curious what @igamigo and @plafer think as well.

**Comment by igamigo** [comment]
I can see some benefit in removing it, but I too tend to prefer keeping the `miden-` prefix for less ambiguity and more consistency (even if marginal), since binary names are currently `miden-node` and `miden-client`. It can also help in searching and identifying files more easily from the outside.

**Pull request merged**
