### PR TITLE
Removed `num_assets` from NoteMetadata

### PR DESCRIPTION
**Pull request by phklive**
Removed `num_assets` from `NoteMetadata` in the miden-node, this will enable the clean update of from the breaking changes made in the miden-base.

Linked to: https://github.com/0xPolygonMiden/miden-base/pull/414

Closes: #169

### CODE REVIEW

**Comment by phklive** [comment]
Hello @bobbinth, here are the changes to remove the `num_assets` from the miden-node. 

I am having a problem when trying to use a non merged branch as a dependency (Here I have used your non merged PR branch for miden-lib and miden-objects to do my PR. I will update to main when your PR is merged).

This is the code that I have updated in the Cargo.toml of the miden-node to use your branch: 

https://github.com/0xPolygonMiden/miden-node/pull/170/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R7-R8

Here is the error that I am having. Would you have a solution?

SCR-20240123-iapq

**Comment by bobbinth** [comment]
> Here is the error that I am having. Would you have a solution?

This is likely because not all miden base dependencies have been updated (i.e., some crates in miden node still point to `next` branch on miden base).

**Comment by phklive** [comment]
> > Here is the error that I am having. Would you have a solution?
> 
> This is likely because not all miden base dependencies have been updated (i.e., some crates in miden node still point to `next` branch on miden base).

Found it thank you, all tests pass.

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! Let's merge after the `miden-base` PR is merged (we'll need to revert changes to `Cargo.toml` files).

**Comment by phklive** [comment]
> Looks good! Thank you! Let's merge after the `miden-base` PR is merged (we'll need to revert changes to `Cargo.toml` files).

Sure, please ping me when merged, I will update and merge when done.

**Pull request merged**
