### PR TITLE
Fix `TODO` for new accounts

### PR DESCRIPTION
**Pull request by phklive**
In this PR I propose to remove the TODO that checks if the transaction was executed against a new account.

I made sure that the transactions initial account hash is indeed equal to `Digest::default()` considering that we received `None` back from the store, meaning that this is a new account.

### CODE REVIEW

**Comment by phklive** [comment]
Question: 

How should we handle old accounts that interact with the node and that are also not recorded in the store?
- Should we simple error out and prevent them from interacting? 
- Is there another thing to do?

**Comment by bobbinth** [comment]
I believe @polydez is working on something that touches the same files. Maybe best to wait until his changes are merged before tackling this one.

> How should we handle old accounts that interact with the node and that are also not recorded in the store?

This should not be possible. If a transaction is against an existing account (i.e., account with `nonce != 0`) but this account is not present in the store, the transaction should be considered invalid.

**Comment by phklive** [comment]
@polydez what's your status on that issue / file?

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
