### PR TITLE
block_producer: server implementation

### PR DESCRIPTION
**Pull request by hackaugusto**
Implements the handler for the submit proven transaction.

### CODE REVIEW

**Comment by hackaugusto** [comment]
marking as ready for review as per @bobbinth 's request.

**Review by plafer — APPROVED** [review]
LGTM

**Comment by plafer** [comment]
Actually, tests fail to compile: `cargo check --all-targets`

**Review by plafer — APPROVED** [review]
LGTM again

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
