### PR TITLE
update: deadpool-sqlite

### PR DESCRIPTION
**Pull request by varun-doshi**
Closes https://github.com/0xPolygonMiden/miden-node/issues/524

### CODE REVIEW

**Comment by Mirko-von-Leipzig** [comment]
Thanks @varun-doshi, could you also commit the `Cargo.lock` file? Our CI checks use `--forced` so its required that the lockfile is up-to-date.

Sorry for the delay; I've been out-of-office.

**Comment by varun-doshi** [comment]
> Thanks @varun-doshi, could you also commit the `Cargo.lock` file? Our CI checks use `--forced` so its required that the lockfile is up-to-date.
> 
> Sorry for the delay; I've been out-of-office.

Done

**Comment by Mirko-von-Leipzig** [comment]
> > Thanks @varun-doshi, could you also commit the `Cargo.lock` file? Our CI checks use `--forced` so its required that the lockfile is up-to-date.
> > Sorry for the delay; I've been out-of-office.
> 
> Done

Ah apologies; I didn't notice that you were working from `main`. We use `next` as our development branch. Could you redo your two commits, but on the `next` branch instead of from `main`?

**Comment by varun-doshi** [comment]
> > > Thanks @varun-doshi, could you also commit the `Cargo.lock` file? Our CI checks use `--forced` so its required that the lockfile is up-to-date.
> > > Sorry for the delay; I've been out-of-office.
> > 
> > 
> > Done
> 
> Ah apologies; I didn't notice that you were working from `main`. We use `next` as our development branch. Could you redo your two commits, but on the `next` branch instead of from `main`?

Done here https://github.com/0xPolygonMiden/miden-node/pull/555

**Pull request closed without merging**
