### PR TITLE
Separate CI into multiple files

### PR DESCRIPTION
**Pull request by phklive**
In this PR I propose the separation of the CI jobs into multiple files enabling more scaling and better separation of concerns.

closes: #268

### CODE REVIEW

**Review by polydez — APPROVED** [review]
Looks good, thanks! How about running these tasks not only for `main`, but also for `next` branch?

**Comment by bobbinth** [comment]
Question: how would this affect the CI badge that we have in the main readme file (see [here](https://github.com/0xPolygonMiden/miden-node/blob/main/README.md?plain=1#L4)).

**Comment by phklive** [comment]
> Question: how would this affect the CI badge that we have in the main readme file (see [here](https://github.com/0xPolygonMiden/miden-node/blob/main/README.md?plain=1#L4)).

Changed the badge from CI to UNIT test to make sure it is still relevant. 

In the future we can or: 
- Remove the badge
- Add more badges ( lint, doc, docker, ... )

Fun fact, hovered around the reth codebase and saw that their badge was also broken haha: https://github.com/paradigmxyz/reth/issues/7158

**Comment by bobbinth** [comment]
> Changed the badge from CI to UNIT test to make sure it is still relevant.

Is there a way to change the label on the badge to `tests`?

Not sure if we need to add lint and doc badges - but maybe some others would be interesting in the future (e.g., `docker` could be interesting). But I do think `tests` we should keep for sure.

**Comment by phklive** [comment]
> > Changed the badge from CI to UNIT test to make sure it is still relevant.
> 
> Is there a way to change the label on the badge to `tests`?
> 
> Not sure if we need to add lint and doc badges - but maybe some others would be interesting in the future (e.g., `docker` could be interesting). But I do think `tests` we should keep for sure.

Changed it to `test` to keep naming convention with the other files being singular.

**Pull request merged**
