### PR TITLE
chore: fix comment

### PR DESCRIPTION
**Pull request by dufucun**

### CODE REVIEW

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you for fixing this.

**Comment by bobbinth** [comment]
Oh - one thing: could you rebase this PR on the `next` branch as that our active development branch?

**Comment by dufucun** [comment]
> Oh - one thing: could you rebase this PR on the `next` branch as that our active development branch?

Changed!

**Comment by dufucun** [comment]
> Oh - one thing: could you rebase this PR on the `next` branch as that our active development branch?

Thans for your reply. In order not to mix with other commits, I will close this PR and submit a new one.

**Pull request closed without merging**
